insert into catalog_item(id, name, image_source, description, amount) values (100, 'Turtle Beach Recon 200 Headset', 'https://images-na.ssl-images-amazon.com/images/I/41SzNJfEQwL._AC_SR400,600_.jpg', 'Powerful amplified audio: Immerse yourself in your games with rechargeable, battery powered amplified sound from your Xbox and PlayStation', 49.95);
insert into catalog_item(id, name, image_source, description, amount) values (200, 'Rustic Town Buffalo Leather Toiletry Bag', 'https://m.media-amazon.com/images/I/51ZYJsc6BhL._AC_SY161_.jpg', 'Multiple Compartments for Essentials: With a roomy interior and numerous compartments, this womens and mens toiletry bag keeps your shaving, personal hygiene & cosmetic products easily accessible.', 31.99);
insert into catalog_item(id, name, image_source, description, amount) values (300, 'Engraved Mini Oak Aging Cask', 'https://m.media-amazon.com/images/I/5175N5yWpyL._AC_SY161_.jpg', 'Medium Charred interior | 10 Liters American Oak Aging Barrel | Barrel Capacity is an approximate', 79.49);
insert into catalog_item(id, name, image_source, description, amount) values (400, 'Deluxe Hot Sauce Kit', 'https://m.media-amazon.com/images/I/516tKLkVRzL._AC_SY161_.jpg', 'All the ingredients you need in one place: make great tasting hot ones hot sauce dabs, with a gourmet spice blend and ancho pasillas, chipotle, habanero and 5x ghost peppers', 49.95);
insert into catalog_item(id, name, image_source, description, amount) values (500, 'This Worx Car Vacuum Cleaner', 'https://m.media-amazon.com/images/I/51cTT8TEgQS._AC_SY161_.jpg', 'Portable, High Power, Handheld Vacuums w/ 3 Attachments, 16 Ft Cord & Bag - 12v, Auto Accessories Kit for Interior Detailing', 34.99);
insert into catalog_item(id, name, image_source, description, amount) values (600, 'TRX All-in-One Suspension Trainer ', 'https://m.media-amazon.com/images/I/81WHuOpgHyL._AC_SX466_.jpg', 'The TRX All-in-One System is the prime suspension trainer for full-body workouts. This system comes with a suspension trainer, a suspension anchor, a door anchor, a getting-started guide and access to the TRX Training Club app.', 99.99);
insert into catalog_item(id, name, image_source, description, amount) values (700, 'UGREEN 100W USB C Wall Charger', 'https://m.media-amazon.com/images/I/61kMoKJEcXL._AC_SX679_.jpg', '4-in-1 Multiport Charger for More Devices: The Ugreen Nexode USB C Charger has 3 USB-C ports and a USB-A port supplying up to 100W of power. Charge a Phone, tablet, laptop, and more at the same time.', 67.99);
insert into catalog_item(id, name, image_source, description, amount) values (800, 'Anker PowerConf C300 Smart Full HD Webcam', 'https://m.media-amazon.com/images/I/61DeUZhKs2L._AC_SX679_.jpg', 'Make a great first impression with clients and impress your boss with PowerConf C300s crisp HD webcam 1080p/60FPS camera with true-to-life colors.', 99.99);
insert into catalog_item(id, name, image_source, description, amount) values (900, 'SAMSUNG 23.5in Curved Computer Monitor', 'https://m.media-amazon.com/images/I/91ubktnbNVL._AC_SX679_.jpg', 'The 1800R curvature of the screen lets you enjoy big, bold and stunning panoramic views while you work or play at home or the office', 139.99);
